const weatherInterpretationCodes = {
  0: { des: 'Clear sky', icon: 'day.svg' },
  1: { des: 'Mainly clear', icon: 'day.svg' },
  2: { des: 'Partly cloudy', icon: 'cloudy.svg' },
  3: { des: 'Overcast', icon: 'cloudy-day-1.svg' },
  45: { des: 'Fog', icon: 'cloudy-day-2.svg' },
  48: { des: 'Depositing rime fog', icon: 'cloudy-day-3.svg' },
  51: { des: 'Light drizzle', icon: 'rainy-1.svg' },
  53: { des: 'Moderate drizzle', icon: 'rainy-2.svg' },
  55: { des: 'Intense drizzle', icon: 'rainy-3.svg' },
  56: { des: 'Light freezing drizzle', icon: 'rainy-1.svg' },
  57: { des: 'Intense freezing drizzle', icon: 'rainy-3.svg' },
  61: { des: 'Light rain', icon: 'rainy-4.svg' },
  63: { des: 'Moderate rain', icon: 'rainy-5.svg' },
  65: { des: 'Heavy rain', icon: 'rainy-6.svg' },
  66: { des: 'Light freezing rain', icon: 'rainy-4.svg' },
  67: { des: 'heavy freezing rain', icon: 'rainy-6.svg' },
  71: { des: 'Light snow', icon: 'snowy-1.svg' },
  73: { des: 'Moderate snow', icon: 'snowy-2.svg' },
  75: { des: 'Heavy snow', icon: 'snowy-3.svg' },
  77: { des: 'Snow grains', icon: 'snowy-1.svg' },
  80: { des: 'Light rain showers', icon: 'rainy-5.svg' },
  81: { des: 'Moderate rain showers', icon: 'rainy-6.svg' },
  82: { des: 'Violent rain showers', icon: 'rainy-7.svg' },
  85: { des: 'Light snow showers', icon: 'snowy-4.svg' },
  86: { des: 'Heavy snow showers', icon: 'snowy-6.svg' },
  95: { des: 'Light thunderstorms', icon: 'thunder.svg' },
  96: { des: 'Thunderstorms with hail', icon: 'thunder.svg' },
  99: { des: 'Severe thunderstorms with hail', icon: 'thunder.svg' },
}

export default weatherInterpretationCodes